teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 0.5
    scale_linear_turbo_x:
      x: 2.0

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.2
    scale_angular_turbo: 
      yaw: 0.5

    enable_button: 6  # L1 shoulder button
    enable_turbo_button: 7  # R1 shoulder button
    enable_x_button: 3  # X button