teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 7
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 0.5
    scale_linear_turbo_x:
      x: 2.0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.2
    scale_angular_turbo: 
      yaw: 0.5

    enable_button: 4  # LB shoulder button
    enable_turbo_button: 5  # RB shoulder button
    enable_x_button: 2  # X button