axis_linear: 7
scale_linear: 0.2
scale_linear_turbo: 0.5
scale_linear_turbo_x: 2.0

axis_angular: 3
scale_angular: 0.2
scale_angular_turbo: 0.5
scale_angular_turbo_x: 2.0

enable_button: 4  # LB shoulder button
enable_turbo_button: 5  # RB shoulder button
enable_x_button: 2  # X button
